'''
-------------LOGIC---------------
We know that there are 10 digits possible i.e. from 0 to 9,
As we want to create the number with the use of a minimum number of digits,
we should use digit 9 as much possible which means for any power PP,
if we want to find out the number for which PP is the power with a minimum number of digits then all the digits are 9 except 1.
If the PP is divisible by 9 then all the digits are 9 only.

'''


# cook your dish here
try:
    t=int(input())
    while t:
        t-=1
        
        # c,r -> represents final power of chef and rick respectively.
        c,r=map(int,input().split())
        
        dc=c//9
        dr=r//9
        if(c%9!=0):
            dc+=1
        if(r%9!=0):
            dr+=1
            
        # Winner along with number of digits of the integer generated by the winner.
        if(dc<dr):
            print(0,dc)
        else:
            print(1,dr)
except Exception:
    pass
